namespace ToyGraf.Models
{
    internal static class DisplayNames
    {
        internal const string
            BackgroundColour = "Background Colour",
            Camera = "Camera",
            CameraView = "Camera View",
            Description = "Description",
            FPS = "FPS",
            GLInfo = "OpenGL Version",
            GLInfo_Extensions = "Extensions",
            GLInfo_Major = "Major Version Number",
            GLInfo_Minor = "Minor Version Number",
            GLInfo_Number = "Version Number",
            GLInfo_Renderer = "Renderer Name",
            GLInfo_Shader = "GLSL Version Number",
            GLInfo_Vendor = "Vendor Name",
            GLMode = "Graphics Mode",
            GLMode_AccumColourFormat = "Accumulator Colour Format",
            GLMode_Buffers = "Buffers",
            GLMode_ColourFormat = "Colour Format",
            GLMode_Depth = "Depth Bits",
            GLMode_Index = "Index",
            GLMode_SampleCount = "Sample Count",
            GLMode_Stencil = "Stencil Bits",
            GLMode_Stereo = "Stereo",
            GPUCode = "GPU Code",
            GPULog = "GPU Log",
            GPUStatus = "GPU Status",
            Location = "Location",
            Maximum = "Maximum",
            Minimum = "Minimum",
            Orientation = "Orientation°",
            Pattern = "Pattern",
            Projection = "Projection",
            ProjectionMatrix = "Projection Matrix",
            Scale = "Scale",
            Shader1Vertex = "Shader 1: Vertex (mandatory)",
            Shader2TessControl = "Shader 2: Tessellation Control",
            Shader3TessEvaluation = "Shader 3: Tessellation Evaluation",
            Shader4Geometry = "Shader 4: Geometry",
            Shader5Fragment = "Shader 5: Fragment (mandatory)",
            Shader6Compute = "Shader 6: Compute",
            StripCount = "Strip Count",
            Title = "Title",
            TraceList = "Traces",
            Transform = "Transform",
            VaoID = "VAO",
            VaoVertexCount = "VAO Vertex Count",
            VboIndexID = "VBO Index Buffer",
            VboVertexID = "VBO Vertex Buffer",
            Visible = "Visible?",
            VSync = "VSync";
    }
}
