namespace ToyGraf.Models
{
    public static class DisplayNames
    {
        public const string
            AccumColourFormat = "Accumulator Colour Format",
            BackgroundColour = "Background Colour",
            Buffers = "Buffers",
            Camera = "Camera",
            CameraView = "Camera View",
            ColourFormat = "Colour Format",
            Depth = "Depth Bits",
            Description = "Description",
            FarPlane = "Far Plane",
            FieldOfView = "Field of View° Y",
            FPS = "FPS",
            GLInfo = "OpenGL Version",
            GLInfo_Extensions = "Extensions",
            GLInfo_Major = "Major Version Number",
            GLInfo_Minor = "Minor Version Number",
            GLInfo_Number = "Version Number",
            GLInfo_Renderer = "Renderer Name",
            GLInfo_Shader = "GLSL Version Number",
            GLInfo_Vendor = "Vendor Name",
            GPUCode = "GPU Code",
            GPULog = "GPU Log",
            GPUStatus = "GPU Status",
            Location = "Location",
            Maximum = "Maximum",
            Minimum = "Minimum",
            NearPlane = "Near Plane",
            Orientation = "Orientation°",
            Pattern = "Pattern",
            Projection = "Projection",
            SampleCount = "Sample Count",
            Scale = "Scale",
            Shader1Vertex = "Shader 1: Vertex (mandatory)",
            Shader2TessControl = "Shader 2: Tessellation Control",
            Shader3TessEvaluation = "Shader 3: Tessellation Evaluation",
            Shader4Geometry = "Shader 4: Geometry",
            Shader5Fragment = "Shader 5: Fragment (mandatory)",
            Shader6Compute = "Shader 6: Compute",
            Stencil = "Stencil Bits",
            Stereo = "Stereo",
            StripCount = "Strip Count",
            Title = "Title",
            Traces = "Traces",
            Transform = "Transform",
            VaoID = "VAO",
            VaoVertexCount = "VAO Vertex Count",
            VboIndexID = "VBO_Index",
            VboVertexID = "VBO_Vertex",
            Visible = "Visible?",
            VSync = "VSync";
    }
}
